IndicoDataSolutions/tf_cod

ipa.tf
* Fixed bad merge
* Converted to helm plugin
* Converted to helm plugin
* Updated to use the actual account name
* Updated to use the actual account name
* Updated to use the actual account name
* Updated the domain to be closer to our aws model
* Added admin_group_name
* Added admin_group_name
* Fixed variable names
* [DOP-1363] allow using ALB instead of ELB. (#30)
* [dop-1363] Pass in values for ACM if in use.
* [dop-1363] fix variable name -dns_name
* [dop-1363] adjust how public subnets are passed in.
* [dop-1363] adjust how public subnets are passed in ... again
* [dop-1363] adjust how public subnets are passed in ... try join
* [dop-1363] adjust how block is passed.
* [dop-1363] fix CAA records. Also use the correct argo application.
* [dop-1363] Create alb values file. Add …
=> 1.0.15.tf cod (#76)

main.tf
- Do not install aws-ebs-csi-driver as an eks add-on.
=> [DOP-1473]

main.tf, variables.tf
QA needs programmatic access to push data to the s3 bucket indico-locust-benchmark-test-results in us-east-2. This enables it optionally with the variable `performance_bucket`. By default that variable is set to false.
=> [DOP-1500] 6.1.0.rc

main.tf, variables.tf
QA needs programmatic access to push data to the s3 bucket indico-locust-benchmark-test-results in us-east-2. This enables it optionally with the variable performance_bucket. By default that variable is set to false.
=> [DOP-1500]

azure/ipa.tf, azure/monitoring.tf, azure/openshift/infrastructure/monitoring.tf, azure/openshift/ipa/ipa.tf, ipa.tf, monitoring.tf
This replaces the default http01-resolver labels in all of our helm charts with dns01-resolver labels
These changes need to also be merged to main and pushed to IPA-6.1.1
=> Dns resolver label 620

ipa.tf, variables.tf
Remove smoketest values in tf_cod if those values are specified in the chart. This prevents duplicates being written to ipa_smoketest.yaml. Duplicates cause an error when the structure of the file is validated when force updating with cluster-on-demand.
This fix will also need to be applied for Azure and Openshift when it is possible to verify the fix on those clusters from the main terraform branch.
The failed checks are for the azure and openshift clusters that did not come up correctly due to other issues filed separately.
=> [DOP-1647] remove hard-coded smoketest values

azure/variables.tf, main.tf, modules/aws/keycloak/keycloak.tf, outputs.tf, user_vars.auto.tfvars, variables.tf
Ended up removing the cluster manager to simplify the way that the aws-auth configmap was managed through the eks module
=> [DOP-1801][DOP-1742] Spot fix

azure/ipa.tf, azure/tf-smoketest-variables.tf, azure/variables.tf, ipa.tf, monitoring.tf, smoketests/common/test_common.py, tf-smoketest-variables.tf, variables.tf
This now installs the external-secret operators helm chart. -https://external-secrets.io/latest/
=> [DOP-1986] Use SQL-exporter instead of postgres-exporter

harness.tf, variables.tf
Changes to be able to configure the number of replicas for the harness delegate
Will probably need to update the `cicd-harness` cluster with this as well
=> [INFRA-105]: Harness Delegate Replicas

azure/monitoring.tf, monitoring.tf, tf-smoketest-variables.tf
Keda was OOMing on dev-ci, we tested it with 4Gi and the problem went away.
=> [DOP-2174] Increase KEDA Ram to 4Gi

main.tf, tf-smoketest-variables.tf, user_vars.auto.tfvars, variables.tf
This is a cost savings measure because it keeps traffic bound for s3 from traversing the NAT gateway. Instead it is able to go from the private subnets directly to s3 with no additional charge.
=> [DOP-2234] Enable s3 VPC Gateway endpoint by default.

main.tf
This fixes an issue where nodes were not able to join the cluster. This was caused by a security group lacking when the vpc endpoints were created. 
- Now using networking module 1.2.2
=> [DOP-2234] Fix

main.tf
This is based on data from [https://grafana.monitoring.us-east-2.indico-devops.indico.io/d/e0f85123-8af1-41ae-9d32-a5078e9ffffc/nod[…]&var-cluster_name=All&var-account_name=wrb](https://grafana.monitoring.us-east-2.indico-devops.indico.io/d/e0f85123-8af1-41ae-9d32-a5078e9ffffc/node-volume-usage?orgId=1&var-cluster_name=All&var-account_name=wrb) which shows that the majority of our clusters use less than 30% of their volumes.
Testing performed:
- Spun up a cod cluster with this version and IPA-6.8.1 and validated smoketests pass
- Spun up a cod cluster with IPA-6.8.1 and validated that smoketests pass., Then updated cluster to this version and verified that the cluster and nodes all updated. After everything settled the smoketests passed again. Please note, it took about 40 minutes for …
=> [dop-2213] Update eks module to Reduce node root volume from 100Gi to 40Gi

main.tf
- Change to using `tf-mod-indico-aws-security-group` version 3.0.0, this will not create a security group if using the `networking` module.
- This change will not require a terraform state migration.
=> [DOP-2268] Fix for security groups

ipa.tf
Remove tag override in migration-operator so that it will default to the tag specified in charts.
=> [DEV-11744] Fix for failing migration jobs

azure/main.tf, main.tf, modules/harness/versions.tf
This is to correct an intermittent issue we have been experiencing where the helm provider is causing terraform cloud to crash.
=> [DOP-2338] Update terraform helm provider to 2.15.0

azure/main.tf, main.tf, modules/harness/versions.tf
This is to fix an intermittent issue with terraform cloud crashes caused by the helm provider version.
=> [DOP-2338] adjust pinned helm provider version

main.tf
This is to fix the terraform error:
Error: Unsupported attribute
on main.tf line 180, in module "lambda-sns-forwarder":
security_group_id    = var.network_module == "networking" ? module.networking.all_subnets_sg_id : module.security-group.all_subnets_sg_id
module.networking is tuple with 1 element
This value does not have any attributes.
=> [dop-2360] Fix security group reference.

oidc.tf
The old groups still exist so we didn't see this issue when I reimplemented keycloak group automation in the summer.
This will fix the group names to match what is currently up to date in keycloak. We should also take a closer look at the logic for the rolebindings here, it looks like engineering might have admin access to devops clusters.
=> [DEV-12943] Fix the rolebindings to point to new group names

main.tf
Tested enabling and disabling the lambda sns forwarder a few times and didn't hit this issue
=> [DEV-13156] Added depends_on for lambda forwarder

azure/harness.tf, harness.tf, modules/harness/main.tf, modules/harness/variables.tf, tf-smoketest-variables.tf, variables.tf
Following harness docs we don't need more than two replicas for the amount of nodes and concurrency pipelines that we have. So I enabled the autoscaling with 2 min replicas to keep HA, add the do-not-evict annotation so cluster autoscaler respect the delegate pod and add affinity to keep pods on different nodes (harness recommends not using the same node for two delates, can cause connectivity issues)
=> Improvements to harness delegate

application.tf
Fix efs csi driver image paths to match current release: https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/charts/aws-efs-csi-driver/values.yaml\#L13-\#L45
=> [DEV-14277] Fix efs csi driver
